### ISSUE TITLE
incorrect translation

### ISSUE THREAD

**Issue by Senpa** [sparkylinux/sparky-aptus-appcenter#2]
https://github.com/sparkylinux/sparky-aptus-appcenter/blob/e1557ba0a446481e8834d31c5ee403f5ff6ba0dd/01-yad/lib/sparky-aptus-appcenter/lang/main/it.js#L25
**replace "Systema" with "Sistema"**

` dict.entries['main']['system'] = "Sistema"; `

**Comment by pavroo** [comment]
updated, thanks
