### ISSUE TITLE
How to enable translations in Yad?

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-aptus-appcenter#5]
The translations files of yad interface stored in `lib/sparky-aptus-appcenter/lang/`, I created translation(WIP) files named `zh_CN.js` under the `apttool` and `main` folders, and then reinstall appcenter by `install.sh`. But the translation doesn't show.

I have no knowledge of javascript, so I can't understand what lang.js means.

How can I enable the translation or what should I named the translation file?

Thanks!

**Comment by pavroo** [comment]
It has to be added to lib/sparky-aptus-appcenter/aptus-appcenter file
